# Generated by Django 4.0.5 on 2022-06-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='handyman',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='health',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='police',
            field=models.IntegerField(null=True),
        ),
    ]
